[docs] Update test instructions
mojotech/scrivener_ecto pull request #110
Opened 2024-09-09 17:02 UTC by kianmeng

Add missing or incorrect step to bootstrap, build, and test the latest Postgres DB using compatible config with Docker-Compose or Podman Compose.

2024-09-10 19:53 UTC, cpjolicoeur requested changes

2024-09-10 19:53 UTC, cpjolicoeur commented on README.md
> +docker-compose up
I'd prefer not to have this directly in the README like this as it implies this is a required step.  I would be open to leaving a note here that speaks to "If you prefer to use docker, then do these steps..." type thing instead.

2024-09-11 14:44 UTC, cpjolicoeur approved these changes

2024-09-11 14:44 UTC, merged

2024-09-11 17:42 UTC, kianmeng commented
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face: