Add prefix support to Scrivener
mojotech/scrivener_ecto pull request #90
Opened 2020-07-29 10:00 UTC by reneweteling

Adds prefix support to Scriviner

2020-08-04 13:21 UTC, drewolson requested changes

2020-08-04 13:21 UTC, drewolson commented on lib/scrivener/paginater/ecto/query.ex
> +    opts = [prefix: Keyword.get_lazy(options, :prefix, fn -> nil end)]
I don't think this needs to be a `get_lazy`, considering we're passing it down inside another `get_lazy` call.

2020-08-04 13:21 UTC, drewolson commented on lib/scrivener/paginater/ecto/query.ex
> +    total_entries = Keyword.get_lazy(options, :total_entries, fn -> total_entries(query, repo, caller, opts) end)
We should just pass the entire `options` down here.

2020-08-04 13:21 UTC, drewolson commented on lib/scrivener/paginater/ecto/query.ex
> +    case Keyword.fetch(opts, :prefix) do
If you're looking to return `nil` in the case `:prefix` isn't found, why use `fetch` rather than `opts[:prefix]`?

2020-08-23 18:54 UTC, tschmidleithner commented
Thanks @reneweteling for bringing this up again. 
This should be closed in favor of #91

2020-08-23 22:54 UTC, closed without merging